### ISSUE TITLE
Test out the waters

### ISSUE THREAD

**Issue by davidgatti** [sequr/sequr-import-avatar#2]
Lets see how can we import user pictures from pingboard to Sequr using their Open API + our Open API. Just need simple node.js script for client.

Test account details : username/password : mishi.patel@gmail.com/Sequrpingboard

sample gist : https://gist.github.com/mishitpatel/bb30ae48e9e21b92c6dc2e12abb40e81

- Pingboard 
- BambooHR

**Comment by mishitpatel** [comment]
High level steps I could think of 
- User generated his API key
- With API key , list all properties
- Choose `property-id`
- For given `property_id`, get the list of all`property_users` 
- For each `property_user` find his photo in HR software with email address 
- Upload profile picture for given `property_user`
