### ISSUE TITLE
Display the list of users

### ISSUE THREAD

**Issue by mishitpatel** [sequr/sequr-import-avatar#24]
Currently we are displaying the user name as its pic gets uploaded and it goes away. 
Instead can we display the names on top of each other and the list stays there. So that we can see which all users have been processed. 

![image](https://user-images.githubusercontent.com/9755412/29669262-d74d4b04-88b0-11e7-8831-aa0bb3adfed1.png)

**Comment by davidgatti** [comment]
If it is ok with you, I'd rather do a summary page, listing all the imported user. What do you think?

**Comment by mishitpatel** [comment]
@davidgatti Either way is fine.
